FROM python:3
MAINTAINER Juan C. Müller <jcmuller@gmail.com>

RUN git clone https://github.com/home-assistant/home-assistant-cli.git /app
ADD . /app
WORKDIR /app
RUN \
  python3 -m venv . && \
  . bin/activate && \
  script/setup

RUN apt-get update; \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    vim-nox \
    && \
  rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/app/bin/python3", "/app/bin/hass-cli"]
CMD ["--help"]
